# Generated by Django 4.0 on 2021-12-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='SportObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzili')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('date_start', models.TimeField(blank=True, null=True, verbose_name='Ochilish vaqti')),
                ('date_end', models.TimeField(blank=True, null=True, verbose_name='Yopilish vaqti')),
                ('work_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISh kunlari')),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
                ('invent_date', models.DateField(blank=True, null=True)),
                ('shower', models.BooleanField(default=False, verbose_name='Yuvunish xonasi')),
                ('changing_room', models.BooleanField(default=False, verbose_name='Kiyim almashtirish xonasi')),
                ('lighting', models.BooleanField(default=False, verbose_name='Yoritish chiroqlari')),
                ('tribunes', models.BooleanField(default=False, verbose_name="O'rindiqlar")),
                ('parking', models.BooleanField(default=False, verbose_name='Parkovka')),
                ('category', models.ManyToManyField(to='sport.Category')),
                ('images', models.ManyToManyField(to='sport.Images')),
            ],
            options={
                'verbose_name': 'Sport obyekti',
                'verbose_name_plural': 'Sport obyektlari',
            },
        ),
    ]
