# Generated by Django 4.0 on 2021-12-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='to`liq ism')),
                ('object_name', models.CharField(max_length=255, verbose_name='obyekt nomi')),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SportObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzili')),
                ('phone', models.CharField(max_length=255, verbose_name='Telefon raqami')),
                ('date_start', models.TimeField(blank=True, null=True, verbose_name='Ochilish vaqti')),
                ('date_end', models.TimeField(blank=True, null=True, verbose_name='Yopilish vaqti')),
                ('work_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='ISh kunlari')),
                ('area', models.CharField(blank=True, max_length=30, null=True)),
                ('invent_date', models.DateField(blank=True, null=True)),
                ('shower', models.BooleanField(default=False, verbose_name='Yuvunish xonasi')),
                ('changing_room', models.BooleanField(default=False, verbose_name='Kiyim almashtirish xonasi')),
                ('lighting', models.BooleanField(default=False, verbose_name='Yoritish chiroqlari')),
                ('tribunes', models.BooleanField(default=False, verbose_name="O'rindiqlar")),
                ('parking', models.BooleanField(default=False, verbose_name='Parkovka')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(blank=True, to='sport.Category')),
                ('images', models.ManyToManyField(blank=True, to='sport.Images')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.objecttype')),
            ],
            options={
                'verbose_name': 'Sport obyekti',
                'verbose_name_plural': 'Sport obyektlari',
            },
        ),
    ]
