# Generated by Django 4.0 on 2021-12-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportobject',
            name='category',
            field=models.ManyToManyField(blank=True, to='sport.Category'),
        ),
        migrations.AlterField(
            model_name='sportobject',
            name='images',
            field=models.ManyToManyField(blank=True, to='sport.Images'),
        ),
    ]
