# Generated by Django 4.0 on 2021-12-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='is_active',
            field=models.CharField(choices=[('new', 'new'), ('accepted', 'accepted'), ('not_accepted', 'not_accepted')], default='new', max_length=255),
        ),
    ]
