# Generated by Django 4.0 on 2021-12-14 10:57

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_sportobject_category_alter_sportobject_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportobject',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=40, max_length=63),
            preserve_default=False,
        ),
    ]
