# Generated by Django 4.0 on 2022-02-01 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0002_alter_orders_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportobject',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
