# Generated by Django 4.0 on 2022-02-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_alter_sportobject_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportobject',
            old_name='user',
            new_name='follower',
        ),
    ]
