# Generated by Django 4.0 on 2021-12-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_objecttype_sportobject_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportobject',
            name='location',
        ),
        migrations.AddField(
            model_name='sportobject',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sportobject',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
