# Generated by Django 4.0 on 2021-12-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_remove_sportobject_location_sportobject_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=2, upload_to='category'),
            preserve_default=False,
        ),
    ]
