# Generated by Django 4.0 on 2022-02-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0006_alter_sportobject_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportobject',
            name='follower',
        ),
    ]
