# Generated by Django 3.2.2 on 2022-02-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0013_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, upload_to='user/'),
        ),
    ]
